# Generated by Django 3.1.7 on 2021-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
